# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

---
# Conditionally disable springdoc on missing api-docs profile
spring:
  config:
    activate:
      on-profile: '!api-docs'
springdoc:
  api-docs:
    enabled: false
---
reactive:
  feign:
    circuit:
      breaker:
        enabled: true
  # client:
  #   config:
  #     default:
  #       connectTimeout: 5000
  #       readTimeout: 5000
management:
  audit:
    events:
      enabled: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"


  endpoint:
    auditevents:
      enabled: true
    shutdown:
      enabled: true
    restart:
      enabled: true
    gateway:
      enabled: true
    health:
      show-details: always
      #roles: 'ROLE_ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
          path: "/management/health/readiness"
          interval_sec: 30
          timeout_sec: 4
          failure_threshold: 2
          success_threshold: 2
        readiness:
          include: readinessState
          path: "/management/health/liveness"
          interval_sec: 30
          timeout_sec: 4
          failure_threshold: 2
          success_threshold: 2
    jhimetrics:
      enabled: true
  info:
    git:
      mode: full
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60
  observations:
    key-values:
      application: ${spring.application.name}
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    data:
      repository:
        autotime:
          enabled: true
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: gatewayapp
  cloud:
    consul:
      host: localhost  # Remove https://
      port: 8500  #
      discovery:
        enabled: true
        #healthCheckPath: /management/health
        #healthCheckAddress: localhost:8080
        instanceId: gatewayapp:cloud:${spring.application.instance-id:${random.value}}
        service-name: gatewayapp
      config:
        watch:
          enabled: false
    gateway:
      forwarded:
        enabled: true
      default-filters:
        - JWTRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          predicates:
            - name: Path
              args:
                pattern: "'/services/'+serviceId.toLowerCase()+'/**'"
          filters:
            - StripPrefix=2
#      routes:
#        - id: auth-service-login
#          uri: lb://auth-service  # Service ID registered with Eureka or your discovery service
#          predicates:
#            - Path=/login
#            - Method=POST
#          filters:
#            - RewritePath=/login, /api/authenticate

      httpclient:
        pool:
          max-connections: 1000
  docker:
    compose:
      enabled: false
      lifecycle-management: start-only
      file: src/main/docker/services.yml
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by gradle when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: '@spring.profiles.active@'
    group:
      dev:
        - dev
        - api-docs
        # Uncomment to activate TLS for the dev profile
        #- tls
  jmx:
    enabled: false
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  webflux:
    problemdetails:
      enabled: true
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
        - USER
    oauth2:
      resourceserver:
        jwt:
          authority-prefix: ''
          authorities-claim-name: auth
          jwk-set-uri: https://example.com/.well-known/jwks.json
  task:
    execution:
      thread-name-prefix: gatewayapp-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: gatewayapp-scheduling-
      pool:
        size: 2
  thymeleaf:
    mode: HTML
  output:
    ansi:
      console-available: true

server:
  servlet:
    session:
      cookie:
        http-only: true

springdoc:
  show-actuator: true

# Properties to be exposed on the /info management endpoint
info:
  # Comma separated list of profiles that will trigger the ribbon to show
  display-ribbon-on-profiles: 'dev'


config:
  clientApp:
    name: 'gatewayappApp'

  # By default CORS is disabled. Uncomment to enable.
  # cors:
  #   allowed-origins: "http://localhost:8100,http://localhost:9000"
  #   allowed-methods: "*"
  #   allowed-headers: "*"
  #   allow-credentials: true
  #   max-age: 1800
  mail:
    from: gatewayapp@localhost
  api-docs:
    default-include-pattern: /api/**
    management-include-pattern: /management/**
    title: Gatewayapp API
    description: Gatewayapp API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license: unlicensed
    license-url:
  security:
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:"


